export const guruBkRoutes = {
    kelas: {
        index: '/guru-bk/kelas',
        store: '/guru-bk/kelas',
        update: (id: number) => `/guru-bk/kelas/${id}`,
        destroy: (id: number) => `/guru-bk/kelas/${id}`,
    },
    siswa: {
        index: '/guru-bk/siswa',
        create: '/guru-bk/siswa/create',
        store: '/guru-bk/siswa',
        show: (id: number) => `/guru-bk/siswa/${id}`,
        edit: (id: number) => `/guru-bk/siswa/${id}/edit`,
        update: (id: number) => `/guru-bk/siswa/${id}`,
        destroy: (id: number) => `/guru-bk/siswa/${id}`,
    },
    siswaKelas: {
        index: '/guru-bk/siswa-kelas',
        update: (id: number) => `/guru-bk/siswa-kelas/${id}`,
        destroy: (id: number) => `/guru-bk/siswa-kelas/${id}`,
        naikKelas: '/guru-bk/siswa-kelas/naik-kelas',
    },
    kategori: {
        index: '/guru-bk/kategori',
        store: '/guru-bk/kategori',
        update: (id: number) => `/guru-bk/kategori/${id}`,
        destroy: (id: number) => `/guru-bk/kategori/${id}`,
    },
    ketersediaan: {
        index: '/guru-bk/ketersediaan',
        template: '/guru-bk/ketersediaan/template',
        blokir: '/guru-bk/ketersediaan/blokir',
        removeBlokir: (id: number) => `/guru-bk/ketersediaan/blokir/${id}`,
    },
    pengajuan: {
        index: '/guru-bk/pengajuan',
        create: '/guru-bk/pengajuan/create',
        store: '/guru-bk/pengajuan',
        show: (id: number) => `/guru-bk/pengajuan/${id}`,
        edit: (id: number) => `/guru-bk/pengajuan/${id}/edit`,
        update: (id: number) => `/guru-bk/pengajuan/${id}`,
        destroy: (id: number) => `/guru-bk/pengajuan/${id}`,
        approve: (id: number) => `/guru-bk/pengajuan/${id}/approve`,
        reject: (id: number) => `/guru-bk/pengajuan/${id}/reject`,
        cancel: (id: number) => `/guru-bk/pengajuan/${id}/cancel`,
    },
    konseling: {
        index: '/guru-bk/konseling',
        show: (id: number) => `/guru-bk/konseling/${id}`,
        inputHasil: (id: number) => `/guru-bk/konseling/${id}/hasil`,
        editHasil: (id: number) => `/guru-bk/konseling/${id}/edit-hasil`,
        updateHasil: (id: number) => `/guru-bk/konseling/${id}/hasil`,
    },
};
